/*! TiledGameEngine v0.0.1 - 10th Mar 2015 | https://github.com/elvariongh/tiledgameengine */
(function(m){var j=!0,l=!1;function s(b,a,d){TiledGameEngine.Stage.call(this,"TiledMapStage",b,a);this.a=d;this.b=[];this.d=l;this.f=[];this.n=this.m=0;this.g=j;this.o=this.p=this.l=this.k=0;this.c=l;this.e=j}var t=new Int32Array(2);new Int32Array(2);s.prototype=Object.create(m.Stage.prototype);
s.prototype.activate=function(){TiledGameEngine.Stage.prototype.activate.call(this);this.screen.layers<this.a.layerscnt?this.screen.addLayer(this.a.layerscnt-this.screen.layers):this.screen.layers>this.a.layerscnt&&this.screen.remLayer(this.screen.layers-this.a.layerscnt);this.screen.clear();this.screen.setBGColor(this.a.bgcolor);this.redraw=j;this.a&&(this.f=[~~(-this.a.mapwidth/2+this.screen.viewport[2]/2),0],this.screen.move(this.f[0],this.f[1]),this.screen.setBoundingBox(-(this.a.mapwidth-this.screen.viewport[2]),
-(this.a.mapheight-this.screen.viewport[3]),this.a.mapwidth-this.screen.viewport[2],this.a.mapheight-this.screen.viewport[3]));this.screen.fade(j)};s.prototype.onViewportResize=function(b,a){TiledGameEngine.Stage.prototype.onViewportResize.call(this,b,a);this.d=l;this.e=this.c=j};s.prototype.onViewportMove=function(b,a){TiledGameEngine.Stage.prototype.onViewportMove.call(this,b,a);this.d=l;this.c=j};
s.prototype.j=function(b,a){b=(b-this.screen.viewport[0]-this.a.mapwidth/2)/this.a.tilewidth;a=(a-this.screen.viewport[1])/this.a.tileheight;t[0]=~~(b+a);t[1]=~~(a-b);return t};s.prototype.update=function(b,a){if(!this.screen||!this.a||!this.active)return 500;if(!this.a.ready)return 100;this.redraw=l;var d,c=this.a.objects.length;if(!c||!this.g)return~~(16-b%16);d=1E3;for(var f=0;f<c;++f){var k=this.a.objects[f];d=Math.min(d,k.update(b,a,this.screen.viewport));this.redraw|=k.redraw}return d};
s.prototype.render=function(){if(this.active&&(this.a&&this.screen)&&this.a.ready){var b=this.screen.viewport;if(!this.d||this.c||this.e)this.h(),this.d=j;this.redraw=l;var a=this.a.layers.length,d=0,c,f;if(this.c)for(this.screen.clear();d<a;++d)c=this.a.layers[d],"tilelayer"===c.type&&(c.visible&&c.properties.render&&!c.properties.mergeWithLayer)&&(f=this.screen.getLayer(c.ctxlayer),f.drawImage(this.b[c.ctxlayer],0,0));this.e=this.c=l;if(f=this.screen.getLayer(this.a.entitiesLayer)){f.clearRect(0,
0,b[2],b[3]);d=0;for(a=this.a.objects.length;d<a;++d)c=this.a.objects[d],c.visible&&c.render(f,this,b)}}};
s.prototype.i=function(b,a,d,c,f,k,n,q){var e=this.a.layers[a];a=e.data;var r=e.screen,p,w=-f;p=-k;var h,g,u,v=this.screen.viewport;if("tilelayer"!==e.type)console.log("ignore (type)",e.name);else if(e.visible)if(e.properties.render)for(;p<=k;p++)for(e=w;e<=f;e++){if(!(e+p&1)&&(h=d+~~((p+e)/2),g=c+~~((p-e)/2),!(0>h||0>g)))if(!(h>=n||g>=q))if(h+=g*n,g=a[h])g=r[5*h+0],0>g||(g=this.a.tilesets[g],(u=this.am.get(g.image))&&b.drawImage(u,r[5*h+1],r[5*h+2],g.tilewidth,g.tileheight,r[5*h+3]+this.a.mapwidth/
2+v[0],r[5*h+4]+v[1],g.tilewidth,g.tileheight))}else console.log("ignore (render)",e.name);else console.log("ignore (visible)",e.name)};
s.prototype.h=function(){var b=0,a,d=this.a.layers.length,c;a=this.screen.viewport;for(var f=this.j(a[2]/2,a[3]/2),k=~~(a[2]/this.a.tilewidth)+2,n=~~(a[3]/this.a.tileheight)+2,q=a[2],e=a[3],k=k>this.a.width?this.a.width:k,n=n>this.a.height?this.a.height:n;b<d;++b)a=this.a.layers[b],"tilelayer"===a.type&&(a.visible&&a.properties.render)&&(this.b[a.ctxlayer]?(c=this.b[a.ctxlayer].getContext("2d"),a.properties.mergeWithLayer||(this.e?(this.b[a.ctxlayer].width=q,this.b[a.ctxlayer].height=e):c.clearRect(0,
0,q,e))):(this.b[a.ctxlayer]=document.createElement("canvas"),this.b[a.ctxlayer].width=q,this.b[a.ctxlayer].height=e,c=this.b[a.ctxlayer].getContext("2d")),this.i(c,b,f[0],f[1],k,n,this.a.width,this.a.height));this.k=this.screen.viewport[0];this.l=this.screen.viewport[1]};m.TiledMapStage=s})(TiledGameEngine);