/*! TiledGameEngine v0.0.1 - 10th Mar 2015 | https://github.com/elvariongh/tiledgameengine */
(function(e) { var d=!0;function f(a,b,c){a||(a="#viewport");c||(c=320);b||(b=200);this.b=[];this.c=void 0;this.d=new Int32Array([-b,-c,b,c]);this.viewport=new Int32Array([0,0,b,c,!1]);this.a=new Int32Array([0,0,0,0,0]);this.layers=0;this.k=window.innerWidth-b;this.j=window.innerHeight-c;this.c=document.querySelector(a);this.c.style.cssText="position:fixed; left: 0px; top:0px; display:none;";this.offsetY=this.offsetX=0;window.addEventListener("resize",throttle(this.i,64,this),d);this.c.addEventListener("mousedown",throttle(this.g,
16,this),d);this.c.addEventListener("mouseup",throttle(this.e,16,this),d);this.c.addEventListener("mousemove",throttle(this.h,64,this),d);this.c.addEventListener("mouseout",throttle(this.e,16,this),d);document.addEventListener("keydown",this.f.bind(this),d);this.addLayer(2);setTimeout(function(){var a=this.c.getClientRects();a.length&&(this.offsetX=a[0].left,this.offsetY=a[0].top)}.bind(this),0)}
f.prototype.f=function(a){switch(a.which){case 33:this.a[3]=-8;this.a[4]=0;break;case 34:this.a[3]=8;this.a[4]=0;break;case 35:this.a[3]=0;this.a[4]=8;break;case 36:this.a[3]=0;this.a[4]=-8;break;case 37:this.a[3]=-2;this.a[4]=0;break;case 38:case 104:this.a[4]=-2;this.a[3]=0;break;case 39:this.a[3]=2;this.a[4]=0;break;case 40:this.a[4]=2;this.a[3]=0;break;case 97:this.a[4]=2;this.a[3]=-2;break;case 99:this.a[4]=2;this.a[3]=2;break;case 105:this.a[4]=-2;this.a[3]=2;break;case 103:this.a[4]=-2;this.a[3]=
-2;break;default:return}this.viewport[0]+this.a[3]>=this.d[0]&&this.viewport[0]+this.viewport[2]+this.a[3]<=this.d[2]?this.viewport[0]+=this.a[3]:this.a[3]=0;this.viewport[1]+this.a[4]>=this.d[1]&&this.viewport[1]+this.viewport[3]+this.a[4]<=this.d[3]?this.viewport[1]+=this.a[4]:this.a[4]=0;(this.a[3]||this.a[4])&&e.bus.notify("onviewportmove")};
f.prototype.g=function(a){a.preventDefault();a.stopImmediatePropagation();a.stopPropagation();this.a[0]=a.clientX-this.offsetX;this.a[1]=a.clientY-this.offsetY;this.a[2]=d};
f.prototype.e=function(a){a.preventDefault();a.stopImmediatePropagation();a.stopPropagation();if(this.a[2]&&(this.a[2]=!1,this.a[3]=a.clientX-this.a[0]-this.offsetX,this.a[4]=a.clientY-this.a[1]-this.offsetY,this.a[3]||this.a[4]))this.viewport[0]+this.a[3]>=this.d[0]&&this.viewport[0]+this.viewport[2]+this.a[3]<=this.d[2]?this.viewport[0]+=this.a[3]:this.a[3]=0,this.viewport[1]+this.a[4]>=this.d[1]&&this.viewport[1]+this.viewport[3]+this.a[4]<=this.d[3]?this.viewport[1]+=this.a[4]:this.a[4]=0,(this.a[3]||
this.a[4])&&e.bus.notify("onviewportmove")};
f.prototype.h=function(a){a.preventDefault();a.stopImmediatePropagation();a.stopPropagation();this.a[3]=a.clientX-this.a[0]-this.offsetX;this.a[4]=a.clientY-this.a[1]-this.offsetY;if(this.a[3]||this.a[4])this.a[2]?(this.viewport[0]+this.a[3]>=this.d[0]&&this.viewport[0]+this.viewport[2]+this.a[3]<=this.d[2]?this.viewport[0]+=this.a[3]:this.a[3]=0,this.viewport[1]+this.a[4]>=this.d[1]&&this.viewport[1]+this.viewport[3]+this.a[4]<=this.d[3]?this.viewport[1]+=this.a[4]:this.a[4]=0,(this.a[3]||this.a[4])&&
e.bus.notify("onviewportmove")):e.bus.notify("mousemove",{x:a.clientX-this.offsetX,y:a.clientY-this.offsetY}),this.a[0]=a.clientX-this.offsetX,this.a[1]=a.clientY-this.offsetY};f.prototype.i=function(a){document.fullscreenEnabled?(this.resize(a.target.innerWidth,a.target.innerHeight),this.offsetX=this.offsetY=0):(this.resize(a.target.innerWidth,a.target.innerHeight),a=this.c.getClientRects(),this.offsetX=a[0].left,this.offsetY=a[0].top)};
f.prototype.resize=function(a,b){for(var c=this.b.length;c--;)this.b[c].canvas.width=this.b[c].width=a,this.b[c].canvas.height=this.b[c].height=b;this.viewport[2]=a;this.viewport[3]=b;this.c.style.width=a+"px";this.c.style.height=b+"px";e.bus&&e.bus.notify("onviewportresize")};f.prototype.move=function(a,b){this.viewport[0]=a;this.viewport[1]=b;e.bus.notify("onviewportmove")};
f.prototype.show=function(a){a!=this.viewport[4]&&(this.c.style.display=a?"block":"none",a&&setTimeout(function(){var a=this.c.getClientRects();this.offsetX=a[0].left;this.offsetY=a[0].top}.bind(this),0));this.viewport[4]=a};
f.prototype.fade=function(a){if(a!=this.viewport[4])if(a){var b=this;(function j(){var a=parseFloat(b.b[0].canvas.style.opacity);isNaN(a)&&(a=0);if(0===a)for(var g=b.b.length;g--;)b.b[g].canvas.style.display="block";if(1<(a+=0.05))e.bus.notify("screenAnimationEnd",{visible:d});else{for(g=b.b.length;g--;)b.b[g].canvas.style.opacity=a;requestAnimationFrame(j)}})()}else b=this,function k(){var a=parseFloat(b.b[0].canvas.style.opacity);isNaN(a)&&(a=1);if(0>(a-=0.05)){for(var h=b.b.length;h--;)b.b[h].canvas.style.display=
"none";e.bus.notify("screenAnimationEnd",{visible:!1})}else{for(h=b.b.length;h--;)b.b[h].canvas.style.opacity=a;requestAnimationFrame(k)}}();this.viewport[4]=a};f.prototype.getLayer=function(a){if(this.b.length>a)return this.b[a]};
f.prototype.addLayer=function(a){a=a||1;for(var b=this.c.innerHTML,c=this.layers;a--;)b+='<canvas style="position:fixed; left: 0px; top: 0px; z-index: '+c+';" id="_tgelr'+c+'"></canvas>',++c;this.c.innerHTML=b;a=c;for(c=0;c<a;++c)this.b[c]=document.getElementById("_tgelr"+c),this.b[c]=this.b[c].getContext("2d");this.layers=a;this.resize(this.viewport[2],this.viewport[3])};
f.prototype.remLayer=function(a){a=a||1;for(var b=this.layers,c=this.c.innerHTML.split("</canvas>"),b=c.length;b--;)0===c[b].length&&(delete c[b],c.splice(b,1));for(b=this.layers;b--;)delete this.b[b];for(b=this.layers;a--;)c.pop(),--b;c=c.join("</canvas>");this.c.innerHTML=c;this.layers=this.b.length=b;for(b=0;b<this.layers;++b)this.b[b]=document.getElementById("_tgelr"+b),this.b[b]=this.b[b].getContext("2d");this.resize(this.viewport[2],this.viewport[3])};
f.prototype.clear=function(a){if(void 0===a)for(a=this.b.length;a--;)this.b[a].clearRect(0,0,this.viewport[2],this.viewport[3]);else(a=this.getLayer(a))&&a.clearRect(0,0,this.viewport[2],this.viewport[3])};f.prototype.setBGColor=function(a){this.c.style.backgroundColor=a};f.prototype.setBoundingBox=function(a,b,c,j){this.d[0]=+a;this.d[1]=+b;this.d[2]=+c;this.d[3]=+j};f.prototype.fullscreen=function(){document.fullscreenEnabled?document.exitFullscreen():this.c.requestFullscreen()};e.ViewPort=f;})(TiledGameEngine);